-- 1. Safely create 'outputs' table if it doesn't exist
create table if not exists public.outputs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure ALL columns exist for 'outputs'
do $$
begin
    -- title
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'title') then
        alter table public.outputs add column title text not null default 'Untitled';
    end if;
    -- description
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'description') then
        alter table public.outputs add column description text;
    end if;
    -- image_url
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'image_url') then
        alter table public.outputs add column image_url text; -- nullable first to avoid error if rows exist
    end if;
    -- link_url
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'link_url') then
        alter table public.outputs add column link_url text;
    end if;
    -- is_featured
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'is_featured') then
        alter table public.outputs add column is_featured boolean default false;
    end if;
    -- category
    if not exists (select 1 from information_schema.columns where table_name = 'outputs' and column_name = 'category') then
        alter table public.outputs add column category text;
    end if;
end $$;


-- 2. Safely create 'slider_content' table
create table if not exists public.slider_content (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure ALL columns exist for 'slider_content'
do $$
begin
    -- title
    if not exists (select 1 from information_schema.columns where table_name = 'slider_content' and column_name = 'title') then
        alter table public.slider_content add column title text;
    end if;
    -- image_url
    if not exists (select 1 from information_schema.columns where table_name = 'slider_content' and column_name = 'image_url') then
        alter table public.slider_content add column image_url text;
    end if;
    -- link_url
    if not exists (select 1 from information_schema.columns where table_name = 'slider_content' and column_name = 'link_url') then
        alter table public.slider_content add column link_url text;
    end if;
    -- order
    if not exists (select 1 from information_schema.columns where table_name = 'slider_content' and column_name = 'order') then
        alter table public.slider_content add column "order" integer default 0;
    end if;
end $$;


-- 3. Enable RLS
alter table public.outputs enable row level security;
alter table public.slider_content enable row level security;


-- 4. Policies (Recreate safely)
drop policy if exists "Public read" on public.outputs;
drop policy if exists "Admin insert" on public.outputs;
drop policy if exists "Admin update" on public.outputs;
drop policy if exists "Admin delete" on public.outputs;

create policy "Public read" on public.outputs for select using (true);
create policy "Admin insert" on public.outputs for insert with check (auth.role() = 'authenticated');
create policy "Admin update" on public.outputs for update using (auth.role() = 'authenticated');
create policy "Admin delete" on public.outputs for delete using (auth.role() = 'authenticated');

drop policy if exists "Public read slider" on public.slider_content;
drop policy if exists "Admin insert slider" on public.slider_content;
drop policy if exists "Admin update slider" on public.slider_content;
drop policy if exists "Admin delete slider" on public.slider_content;

create policy "Public read slider" on public.slider_content for select using (true);
create policy "Admin insert slider" on public.slider_content for insert with check (auth.role() = 'authenticated');
create policy "Admin update slider" on public.slider_content for update using (auth.role() = 'authenticated');
create policy "Admin delete slider" on public.slider_content for delete using (auth.role() = 'authenticated');


-- 5. Storage Bucket (images)
insert into storage.buckets (id, name, public) values ('images', 'images', true)
on conflict (id) do nothing;

drop policy if exists "Public Access Storage" on storage.objects;
drop policy if exists "Auth Upload Storage" on storage.objects;
drop policy if exists "Auth Update Storage" on storage.objects;
drop policy if exists "Auth Delete Storage" on storage.objects;

create policy "Public Access Storage" on storage.objects for select using (bucket_id = 'images');
create policy "Auth Upload Storage" on storage.objects for insert with check (bucket_id = 'images' and auth.role() = 'authenticated');
create policy "Auth Update Storage" on storage.objects for update with check (bucket_id = 'images' and auth.role() = 'authenticated');
create policy "Auth Delete Storage" on storage.objects for delete using (bucket_id = 'images' and auth.role() = 'authenticated');
